name: CI/CD com Vercel

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Instalar dependências
      run: npm install
      working-directory: ./site

    - name: Instalar Jest globalmente
      run: npm install -g jest

    - name: Rodar testes
      run: jest
      working-directory: ./site

    - name: Deploy na Vercel
      run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
      working-directory: ./site

    - name: Notificar sucesso
      if: success()
      run: echo "✅ Pipeline executado com sucesso!"
      
    - name: Notificar falha
      if: failure()
      run: echo "❌ Pipeline falhou!"